"""initial

Revision ID: f0dde358a7f3
Revises: 
Create Date: 2026-04-02 14:08:30.105384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0dde358a7f3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('servers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('ssh_user', sa.String(length=128), nullable=False),
    sa.Column('ssh_key_path', sa.String(length=512), nullable=True),
    sa.Column('ssh_password', sa.String(length=256), nullable=True),
    sa.Column('ssh_port', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_check_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('check_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('check_name', sa.String(length=128), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('running', 'ok', 'incident', 'error', name='check_run_status'), nullable=False),
    sa.Column('signal_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('server_checks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('check_name', sa.String(length=128), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_server_check', 'server_checks', ['server_id', 'check_name'], unique=True)
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('check_run_id', sa.Integer(), nullable=True),
    sa.Column('thread_id', sa.String(length=255), nullable=True),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.Enum('critical', 'warning', 'info', name='incident_severity'), nullable=False),
    sa.Column('problem_type', sa.String(length=128), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('new', 'notified', 'actioned', 'ignored', 'resolved', name='incident_status'), nullable=False),
    sa.Column('action_taken', sa.String(length=128), nullable=True),
    sa.Column('confirmed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['check_run_id'], ['check_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_host_status', 'incidents', ['host', 'status'], unique=False)
    op.create_index('idx_thread', 'incidents', ['thread_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_thread', table_name='incidents')
    op.drop_index('idx_host_status', table_name='incidents')
    op.drop_table('incidents')
    op.drop_index('idx_server_check', table_name='server_checks')
    op.drop_table('server_checks')
    op.drop_table('check_runs')
    op.drop_table('servers')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
